### ISSUE TITLE
Is there any difference between a shakeout test and a smoke test?

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-learn#3]
The "Load testing" article uses the phrase "Shakeout test". This is fine, but the k6 docs use the phrase "Smoke test" for what seems like a similar concept. I also have seen pipe-cleaner test to mean something similar.

To maintain semantic coherence, we should probably aligned workshop terms with docs terms. Maybe we could retitle that section "Smoke test", or if "Shakeout test" is so much better, think about changing the docs.

Of course, we can put as many alternative terms as we want in a non-heading sentence, e.g. "A shakeout test, also called a smoke test or pipe-cleaner test, is a ..."

**Comment by nicolevanderhoeven** [comment]
In practice, "shakeout test" and "smoke test" are used interchangeably. I tend to prefer "shakeout" because smoke implies a fire. :) However, it's not a strong preference.

I do think there is a difference in nuance, though. A shakeout test is typically the first test executed against a new environment/codebase, and only checks that the environment is as expected and that the scripts still work against it. It's usually pretty quick. The name comes from the idea of picking up an environment and giving it a good shake to see if anything falls out.

I think a smoke test tends to run a bit longer and verifies more functionalities. It might exercise more user flows and is a good opportunity to make sure monitoring tools are set up correctly.

With that in mind, wdyt of just saying "A shakeout test, also called a smoke test..." Btw pipe cleaning sounds gross.

**Comment by MattDodsonEnglish** [comment]
> @MattDodsonEnglish wdyt of just saying "A shakeout test, also called a smoke test..." Btw pipe cleaning sounds gross.

Sounds good. It's already in, so closing :-)
