### ISSUE TITLE
Move "clarifying testing" to central workshop toc 

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-learn#8]
The "Checks" topic links to  https://github.com/grafana/k6-learn/blob/main/Modules/Clarifying%20testing%20criteria.md

But this page isn't mentioned in the main ToC of the workshop/course. I think this would be good to highlight. The big-picture topics are probably what k6 docs most lack.

**Comment by nicolevanderhoeven** [comment]
I talked to Pepe about this and he suggested that we keep things as simple as possible for the first iteration of the course/workshop and focus on how to get started with k6. My idea is to talk a bit about each test criterion as we get to it, and then at the end, compare them to each other and provide guidance on which one to use when. 

I started with checks and thresholds in the course, but the others are coming in the next iteration! They're probably more advanced topics anyway. That's why the _Clarifying test criteria_ page has not been deleted. I've [removed the link](https://github.com/grafana/k6-learn/commit/28c987f76935d7864bf250fc001066b865c121ce) for now and will close this, but it's a "yes, this is planned for later".
